Fix zephir Generate libmemcached errors
Error: Zephir\CompilerException: Variable 'servers' cannot be read
because it's not initialized in
/home/vagrant/cphalcon-2.x.x/phalcon/session/adapter/libmemcached.zep on
line 87