Fix fatal error on rendering empty asset collection
The `_collection` property in `Phalcon\Assets\Manager` is null by default, and
implicitly becomes an array when `Phalcon\Assets\Manager::add` is called. This
causes a fatal error when for example `outputJs()` or `outputCss()` is called
without adding resources, which is a normal use case.

    Fatal error: Uncaught exception 'Exception' with message 'The argument is not initialized or iterable()' in phalcon/assets/manager.zep:693