Fixes issue where issent() is called on non-response objects in micro apps
In Micro::handle(), issent() was being called on the return value regardless of type (if the value is an object).
The following error is encountered when the return value's type is not an instance of Phalcon\Http\Response:

Fatal error: Call to undefined function Xyz::issent()