Fix zephir generate View error
Error: Zephir\CompilerException: Cannot read variable 'cache_mode'
because it wasn't declared in
/home/vagrant/cphalcon-2.x.x/phalcon/mvc/view.zep on line 608