Port from:  fix modifyColumn #11437
If currentColumn is missing use column parametr.

prevent:

ERROR: RuntimeException Object
(
    [message:protected] => Trying to call method getname on a non-object
...
)